routes/web.php
<?php

use App\Models\Todo;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TodoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/todos/attivi',[TodoController::class, 'todo_attivi'])->name('todos.attivi');
Route::get('/todos/completati',[TodoController::class, 'todo_completati'])->name('todos.completati');
Route::resource('todos', TodoController::class)->middleware(['auth']);

Route::get('/todos/{id}/completa',[TodoController::class, 'completa'])->name('todos.completa');

app/Models/Todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ConfirmationEmail;
use App\Models\Todo;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todos = Todo::all();

        return view('todos.index',compact('todos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $todo = new Todo;
        $todo->titolo = $request->titolo;
        $todo->testo = $request->testo;
        $todo->priorita = $request->priorita;
        $todo->stato = "1"; //1 corrisponde a attivo 0 a completato
        $todo->save();
        return redirect('/todos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $todo = Todo::find($id);

        return view('todos.edit',compact('todo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $todo = Todo::find($id);
        $todo->titolo = $request->titolo;
        $todo->testo = $request->testo;
        $todo->priorita = $request->priorita;
        $todo->stato = $request->stato;
        if ($todo->stato == '0'){
            $todo->fine = Carbon::now();
        }
        $todo->save();
        return redirect('/todos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todo = Todo::find($id);
        $todo->delete();
        return redirect('/todos');
    }

    public function completa($id)
    {

        $todo = Todo::find($id);
        $todo->stato = '0';
        Mail::to(Auth::user()->email)->send(new ConfirmationEmail($todo, Auth::user()));
        $todo->save();
        return redirect('/todos');
    }

    public function todo_attivi()
    {
        $todos = Todo::where('stato', 1)->get();

        return view('todos.attivi',compact('todos'));
    }

    public function todo_completati()
    {
        $todos = Todo::where('stato', 0)->get();

        return view('todos.completati',compact('todos'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.template')


@section('content')
   <h1>Contenuto</h1>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/nav.blade.php
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('todos.index')}}">Elenco Todo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('todos.attivi')}}">Todo Attivi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('todos.completati')}}">Todo Completati</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{route('todos.create')}}">Inserisci un todo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('logout')}}">Logout</a>
                    </li>
                @endauth
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('login')}}">Entra</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('register')}}">Registrati</a>
                    </li>
                @endguest

            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/layouts/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TodoApp</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/stile.css') }}" rel="stylesheet">
    <!-- include summernote css/js -->
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">


</head>

<body>
@include('layouts.nav')

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            @yield('content')



        </div>
    </div>
</div>


</body>


</html>

resources/views/todos/attivi.blade.php
@extends('layouts.template')


@section('content')
    <h1 class="mt-4">{{  Auth::user()->name }}, visualizza i tuoi todo attivi !</h1>




    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titolo</th>
            <th scope="col">Testo</th>
            <th scope="col">Azioni</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($todos as $todo)
            @php
                if ($todo->priorita == '0'){
                    $colonna = 'table-primary';
                }elseif ($todo->priorita == '1'){
                    $colonna = 'table-warning';
                }else{
                    $colonna = 'table-danger';
                }
            @endphp

            <tr class="@if($todo->stato == 1){{$colonna}}@else table-success @endif">

                <th scope="row">{{ $todo->id }}</th>
                <td>{{ $todo->titolo }}</td>
                <td>{!! $todo->testo  !!}</td>
                <td>
                    <div class="row">
                        <div class="col-3"><a href="/todos/{{ $todo->id }}/edit" class="btn btn-primary"><i class="fas fa-edit"></i></a></div>
                        <div class="col-3">
                            <form method="post" action="{{ route('todos.destroy',$todo->id) }}">
                                @method('DELETE')
                                @csrf
                                <button type="submit" value="Elimina" class="btn btn-primary"><i class="fas fa-trash"></i>
                                </button>
                            </form>
                        </div>
                        <div class="col-3">
                            @if($todo->stato == "1")
                                <a href="/todos/{{ $todo->id }}/completa" class="btn btn-success"><i class="fas fa-check"></i></a>
                            @endif
                        </div>
                    </div>



                </td>

            </tr>

        @endforeach
        </tbody>
    </table>

@endsection

resources/views/todos/completati.blade.php
@extends('layouts.template')


@section('content')
    <h1 class="mt-4">{{  Auth::user()->name }}, visualizza i tuoi todo completati !</h1>




    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titolo</th>
            <th scope="col">Testo</th>
            <th scope="col">Azioni</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($todos as $todo)
            @php
                if ($todo->priorita == '0'){
                    $colonna = 'table-primary';
                }elseif ($todo->priorita == '1'){
                    $colonna = 'table-warning';
                }else{
                    $colonna = 'table-danger';
                }
            @endphp

            <tr class="@if($todo->stato == 1){{$colonna}}@else table-success @endif">

                <th scope="row">{{ $todo->id }}</th>
                <td>{{ $todo->titolo }}</td>
                <td>{!! $todo->testo  !!}</td>
                <td>
                    <div class="row">
                        <div class="col-3"><a href="/todos/{{ $todo->id }}/edit" class="btn btn-primary"><i class="fas fa-edit"></i></a></div>
                        <div class="col-3">
                            <form method="post" action="{{ route('todos.destroy',$todo->id) }}">
                                @method('DELETE')
                                @csrf
                                <button type="submit" value="Elimina" class="btn btn-primary"><i class="fas fa-trash"></i>
                                </button>
                            </form>
                        </div>
                        <div class="col-3">
                            @if($todo->stato == "1")
                                <a href="/todos/{{ $todo->id }}/completa" class="btn btn-success"><i class="fas fa-check"></i></a>
                            @endif
                        </div>
                    </div>



                </td>

            </tr>

        @endforeach
        </tbody>
    </table>

@endsection

resources/views/todos/create.blade.php
@extends('layouts.template')


@section('content')
    <h1 class="mt-4">{{  Auth::user()->name }}, inserisci una nuova cosa da fare !</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('todos.store') }}">
        @csrf
        <label>Titolo Todo</label>
        <input type="text" name="titolo" class="form-control" />



        <label>Testo Todo</label>
        <textarea name="testo" class="form-control"  rows="10" id="mytextarea"></textarea>
        <label>Priorità</label>
        <br>
        <select class="form-control" name="priorita">
            <option value="0">Bassa</option>
            <option value="1">Medio</option>
            <option value="2">Alta</option>
        </select>
        <br />
        <input type="submit" value="Salva Todo" class="btn btn-primary" />
    </form>
@endsection

resources/views/todos/edit.blade.php
@extends('layouts.template')


@section('content')
    <h1 class="mt-4">{{  Auth::user()->name }}, modifica il tuo todo !</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('todos.update',$todo->id) }}">
        @csrf
        @method('PUT')
        <label>Titolo Todo</label>
        <input type="text" name="titolo" class="form-control" value="{{$todo->titolo}}"/>
        <label>Testo Todo</label>
        <textarea name="testo" class="form-control"  rows="10" id="mytextarea">{{$todo->testo}}</textarea>
        <div class="row">
            <div class="col-6">
                <label>Priorità</label>
                <select class="form-control" name="priorita">
                    <option value="0" @if($todo->priorita == '0') selected @endif>Bassa</option>
                    <option value="1" @if($todo->priorita == '1') selected @endif>Medio</option>
                    <option value="2" @if($todo->priorita == '2') selected @endif>Alta</option>
                </select>
            </div>
            <div class="col-6">
                <label>Stato</label>
                <select class="form-control" name="stato">
                    <option value="1" @if($todo->stato == '1') selected @endif>Attivo</option>
                    <option value="0" @if($todo->stato == '0') selected @endif>Completato</option>
                </select>
            </div>
        </div>
        <br>

        <br />
        <input type="submit" value="Modifica Todo" class="btn btn-primary" />
    </form>
@endsection

resources/views/todos/index.blade.php
@extends('layouts.template')


@section('content')
    <h1 class="mt-4">{{  Auth::user()->name }}, visualizza le tue cose da fare !</h1>




    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titolo</th>
            <th scope="col">Testo</th>
            <th scope="col">Azioni</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($todos as $todo)
            @php
                if ($todo->priorita == '0'){
                    $colonna = 'table-primary';
                }elseif ($todo->priorita == '1'){
                    $colonna = 'table-warning';
                }else{
                    $colonna = 'table-danger';
                }
            @endphp

        <tr class="@if($todo->stato == 1){{$colonna}}@else table-success @endif">

            <th scope="row">{{ $todo->id }}</th>
            <td>{{ $todo->titolo }}</td>
            <td>{!! $todo->testo  !!}</td>
            <td>
                <div class="row">
                    <div class="col-3"><a href="/todos/{{ $todo->id }}/edit" class="btn btn-primary"><i class="fas fa-edit"></i></a></div>
                    <div class="col-3">
                        <form method="post" action="{{ route('todos.destroy',$todo->id) }}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" value="Elimina" class="btn btn-primary"><i class="fas fa-trash"></i>
                            </button>
                        </form>
                    </div>
                    <div class="col-3">
                        @if($todo->stato == "1")
                            <a href="/todos/{{ $todo->id }}/completa" class="btn btn-success"><i class="fas fa-check"></i></a>
                        @endif
                    </div>
                </div>



            </td>

        </tr>

        @endforeach
        </tbody>
    </table>

@endsection